### ISSUE TITLE
Difference between Auth / users, Traveler / Locast users and Traveler / locast user profiles

### ISSUE THREAD

**Issue by ghost** [mitmel/OpenLocast-Web#37]
What's the difference between Auth / users, Traveler / Locast users and Traveler / locast user profiles ? I guess Auth is only about users who can access the back-office, but what about the 2 others ?

**Comment by amarkbo** [comment]
Locast Users are a subclass of Django users, this is the reason for the odd setup in the admin site. This means each user will have a LocastUser model, as well as an AuthUser model. Properties concerning the "django" side of things, such as superuser status, and user permissions are in AuthUser. LocastUser contains things specific to the locast platform. The profile contains personal information (bio, etc.) that the user themselves can change.

Note: I am aiming to simplify this since Django 1.5 supports custom user models out of the box: https://docs.djangoproject.com/en/1.5/topics/auth/
